jobs:
  build-and-push:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          docker-context: ./remix-app
          path: ./remix-app
          workspace-root: ./remix-app
          image: remix-app
          no_output_timeout: 20m
          registry-url: us.gcr.io
      - gcp-gcr/tag-image:
          image: remix-app
          registry-url: us.gcr.io
          tag: v$CIRCLE_BUILD_NUM
      - gcp-gcr/push-image:
          image: remix-app
          registry-url: us.gcr.io
          tag: v$CIRCLE_BUILD_NUM
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
version: 2.1
workflows:
  commit:
    jobs:
      - build-and-push

