jobs:
  build-app:
    executer: node/default
    steps:
      - node/run:
          yarn-run: build
      - persist_to_workspace:
          root: .
          paths:
            - .
  build-image-and-push:
    executor: gcp-gcr/default
    steps:
      - attach_workspace:
          at: .
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          docker-context: ./remix-app
          path: ./remix-app
          workspace-root: ./remix-app
          image: remix-app
          tag: v$CIRCLE_BUILD_NUM
          no_output_timeout: 20m
          registry-url: us.gcr.io
      - gcp-gcr/push-image:
          image: remix-app
          registry-url: us.gcr.io
          tag: v$CIRCLE_BUILD_NUM
      - gcp-gcr/tag-image:
          image: remix-app
          registry-url: us.gcr.io
          source-tag: v$CIRCLE_BUILD_NUM
          target-tag: latest 
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  node: circleci/node@5.0.2
version: 2.1
workflows:
  commit:
    jobs:
      - build-app
      - build-image-and-push

