version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  node: circleci/node@5.0.2
  pulumi: pulumi/pulumi@2.1.0
jobs:
  build-app:
      docker:
        - image: 'cimg/base:stable'
      steps:
        - checkout
        - node/install:
            install-yarn: true
            node-version: '18.5'
        - run: cd pulumi && npm install
        - run: cd remix-app && yarn install --frozen-lockfile
        - run: cd remix-app && yarn build
        - persist_to_workspace:
            root: /home/circleci/project
            paths:
              - remix-app
              - pulumi
  build-image-and-push:
    executor: gcp-gcr/default
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          docker-context: ./remix-app
          path: ./remix-app
          workspace-root: ./remix-app
          image: remix-app
          tag: v$CIRCLE_BUILD_NUM
          no_output_timeout: 20m
          registry-url: us.gcr.io
      - gcp-gcr/push-image:
          image: remix-app
          registry-url: us.gcr.io
          tag: v$CIRCLE_BUILD_NUM
      - gcp-gcr/tag-image:
          image: remix-app
          registry-url: us.gcr.io
          source-tag: v$CIRCLE_BUILD_NUM
          target-tag: latest 
  build-infra:
    docker:
      - image: 'cimg/node:18.15.0'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: /home/circleci/project 
      - pulumi/login
      - pulumi/update:
          stack:  dev
          working_directory: /home/circleci/project/pulumi
workflows:
  main-branch-commit:
    jobs:
      - build-app
      - build-image-and-push: 
          requires:
              - build-app
      - build-infra:
          requires:
              - build-image-and-push
