jobs:
  build-app:
      docker:
        - image: 'cimg/base:stable'
      steps:
        - run: mkdir -p app
        - run: cd app
        - run: git clone -b "$CIRCLE_BRANCH" "$CIRCLE_REPOSITORY_URL"
        - node/install:
            install-yarn: true
            node-version: '16.13'
        - run: yarn build
        - persist_to_workspace:
            root: app
            paths:
              - remix-app
  build-image-and-push:
    executor: gcp-gcr/default
    steps:
      - attach_workspace:
          at: app
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          docker-context: app/remix-app
          path: app/remix-app
          workspace-root: app/remix-app
          image: remix-app
          tag: v$CIRCLE_BUILD_NUM
          no_output_timeout: 20m
          registry-url: us.gcr.io
      - gcp-gcr/push-image:
          image: remix-app
          registry-url: us.gcr.io
          tag: v$CIRCLE_BUILD_NUM
      - gcp-gcr/tag-image:
          image: remix-app
          registry-url: us.gcr.io
          source-tag: v$CIRCLE_BUILD_NUM
          target-tag: latest 
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  node: circleci/node@5.0.2
version: 2.1
workflows:
  commit:
    jobs:
      - build-app
      - build-image-and-push

